version: "3.9"

services:
  app:
    build: .
    container_name: contract_management
    restart: unless-stopped
    depends_on:
      - mysql
      - minio
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    env_file:
      - .env
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: contract_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: contract_minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"  # MinIO API
      - "9090:9090"  # MinIO Web UI
    volumes:
      - minio_data:/data
    command: server --console-address ":9090" /data
    networks:
      - app_network

volumes:
  mysql_data:
  minio_data:

networks:
  app_network:
    driver: bridge
